services:
  database:
    image: 'mysql:lts'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: mysql
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
