services:
  database:
    image: 'mysql:lts'
    ports:
      - '3306:3306'
    env_file:
      - ../.env.local
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
volumes:
  mysql_data:
